//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public int record_id { get; set; }
        public string action { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public Nullable<int> changed_by { get; set; }
        public System.DateTime changed_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
