//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batches()
        {
            this.batch_steps = new HashSet<batch_steps>();
            this.quality_controls = new HashSet<quality_controls>();
        }
    
        public int id { get; set; }
        public string batch_number { get; set; }
        public int order_id { get; set; }
        public int recipe_id { get; set; }
        public int tech_map_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string status { get; set; }
        public Nullable<decimal> actual_quantity_kg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch_steps> batch_steps { get; set; }
        public virtual production_orders production_orders { get; set; }
        public virtual recipes recipes { get; set; }
        public virtual tech_maps tech_maps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quality_controls> quality_controls { get; set; }
    }
}
