//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_steps
    {
        public int id { get; set; }
        public int batch_id { get; set; }
        public int step_order { get; set; }
        public string step_name { get; set; }
        public Nullable<decimal> planned_temp_c { get; set; }
        public Nullable<decimal> actual_temp_c { get; set; }
        public Nullable<int> planned_duration_min { get; set; }
        public Nullable<int> actual_duration_min { get; set; }
        public Nullable<decimal> planned_pressure_bar { get; set; }
        public Nullable<decimal> actual_pressure_bar { get; set; }
        public Nullable<int> started_by { get; set; }
        public Nullable<int> completed_by { get; set; }
        public Nullable<System.DateTime> started_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public bool deviation_flag { get; set; }
        public string operator_comment { get; set; }
    
        public virtual batches batches { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
