//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PM20_2Entities1 : DbContext
    {
        public PM20_2Entities1()
            : base("name=PM20_2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audit_log> audit_log { get; set; }
        public virtual DbSet<batch_steps> batch_steps { get; set; }
        public virtual DbSet<batches> batches { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<production_orders> production_orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<quality_controls> quality_controls { get; set; }
        public virtual DbSet<raw_material_batches> raw_material_batches { get; set; }
        public virtual DbSet<raw_materials> raw_materials { get; set; }
        public virtual DbSet<recipe_components> recipe_components { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tech_map_steps> tech_map_steps { get; set; }
        public virtual DbSet<tech_maps> tech_maps { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
