//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_orders()
        {
            this.batches = new HashSet<batches>();
        }
    
        public int id { get; set; }
        public string order_number { get; set; }
        public int recipe_id { get; set; }
        public decimal planned_quantity_kg { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> planned_start_date { get; set; }
        public Nullable<int> created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batches> batches { get; set; }
        public virtual users users { get; set; }
        public virtual recipes recipes { get; set; }
    }
}
