//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quality_controls
    {
        public int id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> raw_material_batch_id { get; set; }
        public System.DateTime analysis_date { get; set; }
        public string sample_type { get; set; }
        public string parameter_name { get; set; }
        public Nullable<decimal> measured_value { get; set; }
        public string standard_value { get; set; }
        public string unit { get; set; }
        public string result { get; set; }
        public string decision { get; set; }
        public Nullable<int> analyst_id { get; set; }
        public string analyst_comment { get; set; }
    
        public virtual batches batches { get; set; }
        public virtual users users { get; set; }
        public virtual raw_material_batches raw_material_batches { get; set; }
    }
}
