//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raw_material_batches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raw_material_batches()
        {
            this.quality_controls = new HashSet<quality_controls>();
        }
    
        public int id { get; set; }
        public int raw_material_id { get; set; }
        public string batch_number { get; set; }
        public string supplier { get; set; }
        public System.DateTime received_date { get; set; }
        public decimal quantity { get; set; }
        public string unit { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quality_controls> quality_controls { get; set; }
        public virtual raw_materials raw_materials { get; set; }
    }
}
