//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tech_map_steps
    {
        public int id { get; set; }
        public int tech_map_id { get; set; }
        public int step_order { get; set; }
        public string step_name { get; set; }
        public string step_type { get; set; }
        public Nullable<decimal> planned_temp_c { get; set; }
        public Nullable<decimal> planned_pressure_bar { get; set; }
        public Nullable<int> planned_duration_min { get; set; }
        public bool is_mandatory { get; set; }
        public string instruction { get; set; }
    
        public virtual tech_maps tech_maps { get; set; }
    }
}
